#pragma once
#define INVALID_COMMAND "Invalid command.\n"
#define NOT_IN_BOOK "The definition is not in the book.\n"
#define NOT_REGISTERED "You are not registered yet.\n"
#define BANNED "You are banned from this library.\n"
#define BORROWED "The book is borrowed.\n"
#define ALREADY_BORROWED "You have already borrowed a book.\n"
#define BAN_MESSAGE "The user %s has been banned from this library.\n"
#define OTHER_BOOK "You didn't borrow this book.\n"
#define ALREADY_REGISTERED "User is already registered.\n"
#define NOT_IN_LIBRARY "The book is not in the library.\n"
